### ISSUE TITLE
Custom converters not considered for top-level Collection and Map-like types

### ISSUE THREAD

**Issue by ursmfamily** [spring-projects/spring-data-cassandra#1181]
I have an entity
```
class EntityA {
   @PrimaryKey
   private Key pk;
   @CassandraType(type = TEXT)
   private org.json.simple.JSONObject jsonObject;
}
```
I have written a JSONToString/StringToJSON writing and reading converter which was working fine with spring-boot version 2.2.13.RELEASE. After upgrading to spring-boot 2.5.4 I'm getting an error while performing a read. In the debug mode I see as typeHint = org.json.simple.JSONObject but the typeHint.isMap() is returning true. 

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter$ConversionContext.convert(MappingCassandraConverter.java:1217)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.getReadValue(MappingCassandraConverter.java:990)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.readProperties(MappingCassandraConverter.java:441)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.doReadEntity(MappingCassandraConverter.java:423)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.doReadEntity(MappingCassandraConverter.java:380)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.doReadEntity(MappingCassandraConverter.java:343)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.doReadRow(MappingCassandraConverter.java:323)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.readRow(MappingCassandraConverter.java:319)
	at org.springframework.data.cassandra.core.convert.MappingCassandraConverter.read(MappingCassandraConverter.java:301)
	at org.springframework.data.cassandra.core.ReactiveCassandraTemplate.lambda$getMapper$32(ReactiveCassandraTemplate.java:952)
	at org.springframework.data.cassandra.core.ReactiveCassandraTemplate.lambda$select$0(ReactiveCassandraTemplate.java:367)
	at org.springframework.data.cassandra.core.cql.ReactiveRowMapperResultSetExtractor.lambda$extractData$0(ReactiveRowMapperResultSetExtractor.java:64)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:103)
```

**Comment by mp911de** [comment]
Thanks for reporting the issue. That is a regression on our side.

**Comment by mp911de** [comment]
Spring Data Cassandra 3.2.6 is released as of yesterday. Note that you need to set the version for Spring Data and not the starter to upgrade it.
