### ISSUE TITLE
Invalid CQL form [keyspace_name]: needs double quotes

### ISSUE THREAD

**Issue by krishna-maersk** [spring-projects/spring-data-cassandra#1362]
Unable to set keyspace name in application.properties or yml, when we provided without quotes it throughs below error

```
Caused by: java.lang.IllegalArgumentException: Invalid CQL form [keyspace_name]: needs double quotes
	at com.datastax.oss.driver.shaded.guava.common.base.Preconditions.checkArgument(Preconditions.java:216) ~[java-driver-shaded-guava-25.1-jre-graal-sub-1.jar:na]
	at com.datastax.oss.driver.api.core.CqlIdentifier.fromCql(CqlIdentifier.java:80) ~[java-driver-core-4.15.0.jar:na]
	at com.datastax.oss.driver.api.core.session.SessionBuilder.withKeyspace(SessionBuilder.java:571) ~[java-driver-core-4.15.0.jar:na]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraSessionBuilder(CassandraAutoConfiguration.java:98) ~[spring-boot-autoconfigure-3.0.4.jar:3.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.6.jar:6.0.6]
	... 103 common frames omitted


```

when we give with double quotes:

`spring.cassandra.keyspace-name="keyspace_name"`

we got below:

```
Caused by: com.datastax.oss.driver.api.core.InvalidKeyspaceException: Invalid keyspace "keyspace_name"
	at com.datastax.oss.driver.api.core.InvalidKeyspaceException.copy(InvalidKeyspaceException.java:34) ~[java-driver-core-4.15.0.jar:na]
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149) ~[java-driver-core-4.15.0.jar:na]
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835) ~[java-driver-core-4.15.0.jar:na]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraSession(CassandraAutoConfiguration.java:87) ~[spring-boot-autoconfigure-3.0.4.jar:3.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.6.jar:6.0.6]
	... 91 common frames omitted


```

setup : 
java 17
`id 'org.springframework.boot' version '3.0.4'`
which includes 
![image](https://user-images.githubusercontent.com/85990691/225827657-de9be86e-530a-4f8a-bc6a-f1de9642cb85.png)

**Comment by mp911de** [comment]
This is Spring Boot code, please file this ticket at https://github.com/spring-projects/spring-boot/issues

**Comment by xzeexcz** [comment]
Did you fix it?

**Comment by Pseudow** [comment]
Did you fixt it?
